version: '3'
services:
  db:
    image: mysql
    volumes:
      - db:/var/lib/mysql
    networks:
      - wp_net
    env_file: .env

  adminer:
    image: adminer
    networks:
      - wp_net
    ports:
      - 8080:8080
    depends_on:
      - db

  wordpress:
    image: wordpress
    networks:
      - wp_net
    ports:
      - 80:80
    volumes:
      - wp_data:/var/www/html
    env_file: .env
    depends_on:
      - db

  sandbox:
    image: bletvaska/swissarmyknife
    networks:
      - wp_net

volumes:
  wp_data:
  db:

networks:
  wp_net:

