version: '3'
services:
  db:
    image: postgres
    volumes:
      - db:/var/lib/postgresql/data
    networks:
      - dp_net
    env_file: .env

  drupal:
    image: drupal
    volumes:
      - drupal-modules:/var/www/html/modules
      - drupal-profiles:/var/www/html/profiles
      - drupal-themes:/var/www/html/themes
      - drupal-sites:/var/www/html/sites
    ports:
      - 80:80
    networks:
      - dp_net
        #env_file: .env
    depends_on:
      - db

volumes:
  db:
  drupal-modules:
  drupal-profiles:
  drupal-themes:
  drupal-sites:

networks:
  dp_net:
