version: '3'
services:
  webserver:
    image: nginx
    ports:
      - 80:80
    volumes:
      - www:/usr/share/nginx/html
    networks:
      - xxx

  rambo:
    image: bletvaska/rambo
    ports:
      - 8080:80
    networks:
      - xxx

networks:
  xxx:

volumes:
  www:
